---

- name: add SafeEyes ppa
  apt_repository:
    repo: 'ppa:slgobinath/safeeyes'

- name: install SafeEyes
  apt:
    name: '{{ item.name }}'
    state: '{{ item.state | default("present") }}'
    update_cache: yes

  with_items:
    - name: safeeyes

- name: install desktop apps
  apt:
    name: '{{ item.name }}'
    state: '{{ item.state | default("present") }}'
    purge: yes

  with_items:
    - name: chromium-browser
    - name: gimp
    - name: gnucash
    - name: ibus-chewing
    - name: python-gpg # For Dropbox
    - name: nautilus-dropbox
    - name: ubuntu-restricted-extras
    - name: gnome-tweak-tool
    - name: redshift-gtk

- name: install Google Chrome
  apt:
    deb: 'https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb'

- name: configure dock
  shell: |
    gsettings set org.gnome.shell.extensions.dash-to-dock click-action 'minimize'
    gsettings set org.gnome.shell.extensions.dash-to-dock autohide true
    gsettings set org.gnome.shell.extensions.dash-to-dock show-apps-at-top true
  become: false

- name: move window bottons to left
  shell: gsettings set org.gnome.desktop.wm.preferences button-layout 'close,maximize,minimize:'
  become: false

- name: enable geoclue for redshift
  blockinfile:
    path: /etc/geoclue/geoclue.conf
    block: |
      
      [redshift]
      allowed=true
      system=false
      users=
