---
- name: install dep
  apt:
    name: '{{ item.name }}'
    state: '{{ item.state | default("present") }}'
    purge: yes

  with_items:
    - name: git-core
    - name: gnupg-agent
    - name: gnupg2
    - name: libusb-1.0-0-dev
    - name: pcscd
    - name: pinentry-curses
    - name: pwgen
    - name: scdaemon
    - name: tree
    - name: xclip
    - name: yubikey-personalization
    - name: zsh

- name: download pass
  get_url:
    url: 'https://git.zx2c4.com/password-store/snapshot/password-store-1.7.1.tar.xz'
    dest: /tmp/password-store-1.7.1.tar.xz
    checksum: 'sha256:f6d2199593398aaefeaa55e21daddfb7f1073e9e096af6d887126141e99d9869'

- name: unarchive
  unarchive:
    src: /tmp/password-store-1.7.1.tar.xz
    dest: /tmp

- name: install pass
  make:
    chdir: /tmp/password-store-1.7.1
    target: install

- name: download Tomb
  get_url:
    url: 'https://files.dyne.org/tomb/Tomb-2.5.tar.gz'
    dest: /tmp/Tomb-2.5.tar.gz
    checksum: 'sha256:8c03693cd4aa1fa7eccbad55dec02474750be7b75180b51f1085ab671bc58689'

- name: unarchive
  unarchive:
    src: /tmp/Tomb-2.5.tar.gz
    dest: /tmp

- name: install tomb
  make:
    chdir: /tmp/Tomb-2.5
    target: install

- name: download pass-tomb
  get_url:
    url: 'https://github.com/roddhjav/pass-tomb/releases/download/v1.1/pass-tomb-1.1.tar.gz'
    dest: /tmp/pass-tomb-1.1.tar.gz
    checksum: 'sha256:38fd010e9105b86935d1ae5add5ea4fca9e52feb728169abb4194c73468f8a42'

- name: unarchive
  unarchive:
    src: /tmp/pass-tomb-1.1.tar.gz
    dest: /tmp

- name: install pass-tomb
  make:
    chdir: /tmp/pass-tomb-1.1
    target: install
