---

-   apt_repository:
        repo: 'ppa:webupd8team/java'

-   apt:
        name: '{{ item.name }}'
        state: '{{ item.state | default("present") }}'
        update_cache: yes

    with_items:
        -   name: debconf-utils

-   debconf:
        name: oracle-java9-installer
        question: shared/accepted-oracle-license-v1-1
        vtype: select
        value: true

-   debconf:
        name: oracle-java9-installer
        question: shared/accepted-oracle-license-v1-1
        vtype: seen
        value: true

-   apt:
        name: '{{ item.name }}'
        state: '{{ item.state | default("present") }}'

    with_items:
        -   name: python-software-properties
        -   name: oracle-java9-installer
        -   name: ca-certificates
        -   name: oracle-java9-set-default
