---

- name: add Java ppa
  apt_repository:
    repo: 'ppa:webupd8team/java'

- name: install debconf
  apt:
    name: '{{ item.name }}'
    state: '{{ item.state | default("present") }}'
    update_cache: yes

  with_items:
    - name: debconf-utils

- name: accept license
  debconf:
    name: oracle-java9-installer
    question: shared/accepted-oracle-license-v1-1
    vtype: select
    value: true

- name: mark license as seen
  debconf:
    name: oracle-java9-installer
    question: shared/accepted-oracle-license-v1-1
    vtype: seen
    value: true

- name: install Java
  apt:
    name: '{{ item.name }}'
    state: '{{ item.state | default("present") }}'

  with_items:
    - name: python-software-properties
    - name: oracle-java9-installer
    - name: ca-certificates
    - name: oracle-java9-set-default
