---

-   apt:
        deb: http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/cuda-repo-ubuntu1604_8.0.61-1_amd64.deb

-   service:
        name: lightdm
        state: stopped

-   apt:
        name: cuda
        state: present
        update_cache: yes
