---

- name: download Anaconda
  get_url:
    url: 'https://repo.anaconda.com/archive/Anaconda3-5.1.0-Linux-x86_64.sh'
    dest: /tmp/Anaconda3-5.1.0-Linux-x86_64.sh
    mode: '0755'
  become: false

- name: install Anaconda
  command: bash /tmp/Anaconda3-5.1.0-Linux-x86_64.sh -b -p {{ ansible_env.HOME }}/anaconda3
  args:
    creates: '{{ ansible_env.HOME }}/anaconda3'
  become: false

- name: create Python 2 environment
  command: '{{ ansible_env.HOME }}/anaconda3/bin/conda create -n py27 -y python=2.7 anaconda'
  args:
    creates: '{{ ansible_env.HOME }}/anaconda3/envs/python27/bin/python'
  become: false

- name: install default packages
  command: '{{ ansible_env.HOME }}/anaconda3/bin/conda install -n py27 neovim flake8 pylint yapf -c conda-forge -y'
  become: false

- name: create Python 3 environment
  command: '{{ ansible_env.HOME }}/anaconda3/bin/conda create -n py36 -y python=3.6 anaconda'
  args:
    creates: '{{ ansible_env.HOME }}/anaconda3/envs/python36/bin/python'
  become: false

- name: install default packages
  command: '{{ ansible_env.HOME }}/anaconda3/bin/conda install -n py36 neovim flake8 pylint yapf -c conda-forge -y'
  become: false
