---

- name: install related packages
  apt:
    name: '{{ item.name }}'
    state: '{{ item.state | default("present") }}'

  with_items:
    - name: build-essential
    - name: cmake
    - name: python3-dev
    - name: neovim
