---

- name: add nvim ppa
  apt_repository: repo='ppa:neovim-ppa/stable' state=present

- name: install related packages
  apt:
    name: '{{ item.name }}'
    state: '{{ item.state | default("present") }}'
    update_cache: yes

  with_items:
    - name: build-essential
    - name: cmake
    - name: python3-dev
    - name: neovim
